package com.eureka.firma.digital.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-29T19:29:07.780-06:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://service.ws.digital.firma.eureka.com/", name = "IFirmaElectronica")
@XmlSeeAlso({ObjectFactory.class})
public interface IFirmaElectronica {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "firmarArchivo", targetNamespace = "http://service.ws.digital.firma.eureka.com/", className = "com.eureka.firma.digital.ws.service.FirmarArchivo")
    @WebMethod
    @ResponseWrapper(localName = "firmarArchivoResponse", targetNamespace = "http://service.ws.digital.firma.eureka.com/", className = "com.eureka.firma.digital.ws.service.FirmarArchivoResponse")
    public com.eureka.firma.digital.ws.service.RespuestaFirma firmarArchivo(
        @WebParam(name = "solicitudFirma", targetNamespace = "")
        com.eureka.firma.digital.ws.service.SolicitudFirma solicitudFirma
    );
}
