
package com.eureka.firma.digital.ws.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-29T19:29:07.733-06:00
 * Generated source version: 2.7.6
 * 
 */
public final class IFirmaElectronica_FirmaElectronicaServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ws.digital.firma.eureka.com/", "FirmaElectronicaService");

    private IFirmaElectronica_FirmaElectronicaServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FirmaElectronicaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FirmaElectronicaService ss = new FirmaElectronicaService(wsdlURL, SERVICE_NAME);
        IFirmaElectronica port = ss.getFirmaElectronicaServiceImplPort();  
        
        {
        
            com.eureka.firma.digital.ws.service.SolicitudFirma _firmarArchivo_solicitudFirma = null;
            com.eureka.firma.digital.ws.service.RespuestaFirma _firmarArchivo__return = port.firmarArchivo(_firmarArchivo_solicitudFirma);
        

        }

        System.exit(0);
    }

}
